### ISSUE TITLE
python3 setuptools install error while installing pylucene in ubuntu

### ISSUE THREAD

**Issue by Dhanya-2003** [coady/homebrew-tap#8]
Hi,

While I were installing "PyLucene" in ubuntu 22.04.2 LTS, error message as follows occurred.

python3 -c import setuptools... --no-user-cfg install --prefix=/home/linuxb
Last 15 lines from /home/h532671/.cache/Homebrew/Logs/pylucene/01.python3:
gcc-11 -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -D_java_generics -DJCC_VER=\"3.11\" -I/home/linuxbrew/.linuxbrew/opt/openjdk/libexec/include -I/home/linuxbrew/.linuxbrew/opt/openjdk/libexec/include/linux -I_jcc3 -Ijcc3/sources -I/home/linuxbrew/.linuxbrew/opt/python@3.11/include/python3.11 -c jcc3/sources/JArray.cpp -o build/temp.linux-x86_64-cpython-311/jcc3/sources/JArray.o -DPYTHON -fno-strict-aliasing -Wno-write-strings
gcc-11 -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -D_java_generics -DJCC_VER=\"3.11\" -I/home/linuxbrew/.linuxbrew/opt/openjdk/libexec/include -I/home/linuxbrew/.linuxbrew/opt/openjdk/libexec/include/linux -I_jcc3 -Ijcc3/sources -I/home/linuxbrew/.linuxbrew/opt/python@3.11/include/python3.11 -c jcc3/sources/JCCEnv.cpp -o build/temp.linux-x86_64-cpython-311/jcc3/sources/JCCEnv.o -DPYTHON -fno-strict-aliasing -Wno-write-strings
gcc-11 -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -D_java_generics -DJCC_VER=\"3.11\" -I/home/linuxbrew/.linuxbrew/opt/openjdk/libexec/include -I/home/linuxbrew/.linuxbrew/opt/openjdk/libexec/include/linux -I_jcc3 -Ijcc3/sources -I/home/linuxbrew/.linuxbrew/opt/python@3.11/include/python3.11 -c jcc3/sources/JObject.cpp -o build/temp.linux-x86_64-cpython-311/jcc3/sources/JObject.o -DPYTHON -fno-strict-aliasing -Wno-write-strings
gcc-11 -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -D_java_generics -DJCC_VER=\"3.11\" -I/home/linuxbrew/.linuxbrew/opt/openjdk/libexec/include -I/home/linuxbrew/.linuxbrew/opt/openjdk/libexec/include/linux -I_jcc3 -Ijcc3/sources -I/home/linuxbrew/.linuxbrew/opt/python@3.11/include/python3.11 -c jcc3/sources/functions.cpp -o build/temp.linux-x86_64-cpython-311/jcc3/sources/functions.o -DPYTHON -fno-strict-aliasing -Wno-write-strings
In file included from /home/linuxbrew/.linuxbrew/opt/python@3.11/include/python3.11/Python.h:44,
                 from _jcc3/java/lang/Object.h:18,
                 from jcc3/sources/functions.cpp:23:
jcc3/sources/functions.cpp: In function ‘void installType(PyTypeObject**, PyType_Def*, PyObject*, char*, int)’:
/home/linuxbrew/.linuxbrew/opt/python@3.11/include/python3.11/object.h:136:30: error: lvalue required as left operand of assignment
  136 | #  define Py_TYPE(ob) Py_TYPE(_PyObject_CAST(ob))
      |                       ~~~~~~~^~~~~~~~~~~~~~~~~~~~
jcc3/sources/functions.cpp:1742:13: note: in expansion of macro ‘Py_TYPE’
 1742 |             Py_TYPE(*type) = PY_TYPE(FinalizerClass);
      |             ^~~~~~~
error: command '/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-11' failed with exit code 1

Please help me and thank you in advance.

**Comment by coady** [comment]
I'm not able to build the formula anymore either:
* the [existing build](https://github.com/coady/homebrew-tap/actions/workflows/build.yml) - with no changes - started failing with permission errors
* PyLucene 9 has switched to using gradle, which is causing a different build error
* the old version of gradle is incompatible with recent versions of JDK
* I'm on ARM locally - which homebrew linux doesn't support - making debugging difficult
